name: Deploy Google Sheet To Json Documentation
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: |
          npm install --prefix=./documentation
          npm run build --prefix=./documentation

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: docs
          folder: documentation/build
